name: Pull Request Workflow
on: pull_request
jobs:
  build-parser:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.1"
      - run: go build .
        working-directory: parser/
  build-grabber:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.1"
      - run: go build .
        working-directory: grabber/
